services:
  aws-setup:
    image: pulumi/pulumi-nodejs:3.136.1
    container_name: 'ecamp3-aws-setup'
    volumes:
      - ../../.prettierrc:/.prettierrc:delegated
      - ../../.cache/npm:/root/.npm/_cacache:delegated
      - ./:/aws-setup:delegated
      - ./.aws:/root/.aws:delegated
      - ./.pulumi:/root/.pulumi:delegated
    working_dir: /aws-setup
    environment:
      - AWS_DEFAULT_REGION=eu-west-3

  aws-cli:
    image: amazon/aws-cli:2.18.8
    container_name: 'ecamp3-aws-cli'
    volumes:
      - ./.aws:/root/.aws:delegated
    working_dir: /aws-setup
    environment:
      - AWS_DEFAULT_REGION=eu-west-3
