# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  # aliased to 5.3.10
  - 5.3

# optionally specify a list of environments, for example to test different RDBMS
# env:
  - DB=mysql
#   - DB=pgsql

# execute any number of scripts before the test run, custom env's are available as variables
# before_script:
#   - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
#   - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS eCamp3dev_UnitTest;" -uroot; fi

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
# script: phpunit --configuration phpunit_$DB.xml --coverage-text


script: phpunit --configuration phpunit.xml

branches:
  only:
    - devel
