api_platform:
    title: eCamp v3
    version: 1.0.0
    show_webby: false
    enable_link_security: true
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/DTO'
    formats:
        jsonhal: [ 'application/hal+json' ]
        jsonld: [ 'application/ld+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
        json: [ 'application/json' ]
        html: [ 'text/html' ]
    docs_formats:
        jsonhal: [ 'application/hal+json' ]
        jsonld: [ 'application/ld+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
        jsonopenapi: ['application/vnd.openapi+json']
        html: [ 'text/html' ]
    patch_formats:
        json: [ 'application/merge-patch+json' ]
    error_formats:
        jsonproblem: [ 'application/problem+json' ]
        jsonld: [ 'application/ld+json' ]
    swagger:
        versions: [3]
    defaults:
        stateless: true
        pagination_enabled: false
        itemOperations: [ 'get', 'patch', 'delete' ]
        collection_operations:
            get: ~
            post:
                input_formats: [ 'jsonld', 'jsonapi', 'json' ]
        normalization_context:
            skip_null_values: false
        order:
            createTime: DESC
