name: Fast Forward Merge

on:
  issue_comment:
    types: [ created ]

jobs:
  fast_forward_job:
    name: Fast Forward
    if: |
      (github.event.issue.pull_request != '') &&
      github.event.comment.body == '/fast-forward' &&
      contains(github.event.comment.author_association, 'OWNER')
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Basic use case example
      - name: Fast Forward PR
        id: ff-action
        uses: endre-spotlab/fast-forward-js-action@2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          success_message: 'Success! Fast forwarded ***target_base*** to ***source_head***! ```git checkout target_base && git merge source_head --ff-only``` '
          failure_message: 'Failed! Cannot do fast forward!'
